from typing import Any, Callable, List, Optional, Union
from pathlib import Path

class Observer:
    def __init__(self): ...
    def schedule(self, event_handler, path: Union[str, Path], recursive: bool = False) -> Any: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def join(self, timeout: Optional[float] = None) -> None: ...
    def is_alive(self) -> bool: ...